[package]
name = "eggfetch-cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "Command-line interface for eggfetch"

[lints]
workspace = true

[[bin]]
name = "eggfetch"
path = "src/main.rs"

[dependencies]
eggfetch-core = { path = "../eggfetch-core" }