[package]
name = "eggfetch-python"
version = "0.1.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "Python bindings for eggfetch"

[lints]
workspace = true

[features]
default = ["proxy"]
proxy = ["eggfetch-core/proxy"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
eggfetch-core = { version = "0.1.1", path = "../eggfetch-core", features = ["cookies", "multipart", "proxy", "compression-gzip", "compression-brotli", "compression-zstd", "compression-deflate", "http2", "http3"] }
pyo3 = { version = "0.23", features = ["extension-module"] }
pyo3-async-runtimes = { version = "0.23", features = ["tokio-runtime"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "net", "fs"] }
tokio-rustls = { version = "0.26", default-features = false, features = ["logging", "tls12"] }
rustls = { version = "0.23", default-features = false, features = ["std", "tls12", "ring"] }
webpki-roots = "0.26"
bytes = "1"
encoding_rs = "0.8"
futures-util = "0.3"
http = "1"
url = "2"

[build-dependencies]
pyo3-build-config = "0.23"
