"""Reviewed stubs for the private PyO3 extension.

The extension is private at runtime.  The public package imports the names
listed explicitly in ``__init__.pyi``; the type aliases below are typing-only
conveniences and are not runtime exports.
"""

from collections.abc import AsyncIterable, AsyncIterator, Iterable, Iterator, Mapping, Sequence
import ssl
from typing import Any, Self, TypeAlias

BytesLike: TypeAlias = bytes | bytearray | memoryview
SyncBody: TypeAlias = BytesLike | str | Iterable[BytesLike | str]
AsyncBody: TypeAlias = AsyncIterable[BytesLike | str]
HeadersInput: TypeAlias = Mapping[str, str] | Sequence[tuple[str, str]]
Auth: TypeAlias = BasicAuth | BearerAuth | NoAuth
Verify: TypeAlias = bool | str | ssl.SSLContext
Cert: TypeAlias = str | tuple[str, str]


class EggfetchError(Exception): ...
class RequestError(EggfetchError): ...
class InvalidUrl(RequestError): ...
class TimeoutException(RequestError): ...
class PoolTimeout(TimeoutException): ...
class ConnectTimeout(TimeoutException): ...
class ReadTimeout(TimeoutException): ...
class WriteTimeout(TimeoutException): ...
class NetworkError(RequestError): ...
class ProtocolError(RequestError): ...
class BodyError(RequestError): ...
class DecompressionError(RequestError): ...
class UnsupportedContentEncoding(RequestError): ...
class TooManyRedirects(RequestError): ...
class ProxyError(RequestError): ...
class ProxyConnectError(ProxyError): ...
class ProxyAuthError(ProxyError): ...
class BodyNotReplayableForRetry(RequestError): ...
class RetryBudgetExhausted(RequestError): ...
class RetryNotConfigured(RequestError): ...
class Http2Error(RequestError): ...
class Http2GoAway(Http2Error): ...
class Http2StreamReset(Http2Error): ...
class Http2FlowControlError(Http2Error): ...
class H3Error(RequestError): ...
class H3ConnectError(H3Error): ...
class H3ProtocolError(H3Error): ...
class HTTPStatusError(EggfetchError): ...
class UnsupportedKwarg(EggfetchError): ...
class StreamConsumed(EggfetchError): ...
class StreamClosed(EggfetchError): ...
class ResponseNotRead(EggfetchError): ...


class Headers:
    def __init__(self, value: HeadersInput | None = ..., **kwargs: str) -> None: ...
    def __getitem__(self, key: str) -> str: ...
    def __contains__(self, key: object) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def get(self, key: str, default: str | None = ...) -> str | None: ...
    def keys(self) -> Iterator[str]: ...
    def values(self) -> Iterator[str]: ...
    def items(self) -> Iterator[tuple[str, str]]: ...
    def get_list(self, key: str) -> list[str]: ...


class Cookie: ...


class Cookies:
    def __init__(self) -> None: ...
    def get(self, name: str, default: str | None = ...) -> str | None: ...
    def set(self, name: str, value: str, *, domain: str | None = ..., path: str = ...) -> None: ...
    def clear(self) -> None: ...
    def values(self) -> Iterator[str]: ...
    def items(self) -> Iterator[tuple[str, str]]: ...


class Timeout:
    def __init__(
        self,
        seconds: float | None = ...,
        *,
        pool: float | None = ...,
        connect: float | None = ...,
        write: float | None = ...,
        read: float | None = ...,
        total: float | None = ...,
    ) -> None: ...
    def has_any(self) -> bool: ...


class Limits:
    def __init__(
        self,
        *,
        max_connections: int | None = ...,
        max_keepalive_connections: int | None = ...,
        keepalive_expiry: float | None = ...,
        max_connections_per_host: int | None = ...,
    ) -> None: ...


class Retry:
    def __init__(
        self,
        max_attempts: int = ...,
        backoff_factor: float = ...,
        max_delay: float = ...,
        initial_delay: float = ...,
        statuses: Sequence[int] | None = ...,
        respect_retry_after: bool = ...,
        allow_post: bool = ...,
        allow_put: bool = ...,
        allow_delete: bool = ...,
        allow_patch: bool = ...,
        max_elapsed: float | None = ...,
    ) -> None: ...


class BasicAuth:
    def __init__(self, username: str, password: str = ...) -> None: ...


class BearerAuth:
    def __init__(self, token: str) -> None: ...


class NoAuth: ...
NOAUTH: NoAuth


class File:
    def __init__(self, path: str, *, filename: str | None = ..., content_type: str | None = ...) -> None: ...


class NetworkStream:
    def read(self, max_bytes: int = ..., timeout: float | None = ...) -> bytes: ...
    def write(self, data: bytes, timeout: float | None = ...) -> None: ...
    def close(self) -> None: ...
    def get_extra_info(self, key: str) -> str | None: ...
    def start_tls(self, ssl_context: ssl.SSLContext | None, server_hostname: str, *, timeout: float | None = ...) -> None: ...


class AsyncNetworkStream:
    async def read(self, max_bytes: int = ..., timeout: float | None = ...) -> bytes: ...
    async def write(self, data: bytes, timeout: float | None = ...) -> None: ...
    async def aclose(self) -> None: ...
    def get_extra_info(self, key: str) -> str | None: ...
    async def start_tls(self, ssl_context: ssl.SSLContext | None, server_hostname: str, *, timeout: float | None = ...) -> None: ...


class Response:
    status_code: int
    headers: Headers
    url: str
    reason_phrase: str
    http_version: str
    history: list[Response]
    cookies: Cookies
    extensions: dict[str, Any]
    content: bytes
    text: str
    def json(self, **kwargs: Any) -> Any: ...
    def iter_bytes(self, *args: Any, **kwargs: Any) -> Iterator[bytes]: ...
    def iter_text(self, *args: Any, **kwargs: Any) -> Iterator[str]: ...
    def iter_lines(self) -> Iterator[str]: ...
    def raise_for_status(self) -> Response: ...
    def close(self) -> None: ...
    async def aclose(self) -> None: ...


class StreamingResponse(Response):
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...
    def iter_bytes(self, *, chunk_size: int = ...) -> Iterator[bytes]: ...
    def iter_text(self, *, chunk_size: int = ..., encoding: str | None = ...) -> Iterator[str]: ...
    def iter_lines(self, *, chunk_size: int = ..., encoding: str | None = ...) -> Iterator[str]: ...
    def iter_raw(self, *, chunk_size: int | None = ...) -> Iterator[bytes]: ...
    def aiter_bytes(self, *, chunk_size: int = ...) -> AsyncIterator[bytes]: ...
    def aiter_text(self, *, chunk_size: int = ..., encoding: str | None = ...) -> AsyncIterator[str]: ...
    def aiter_lines(self, *, chunk_size: int = ..., encoding: str | None = ...) -> AsyncIterator[str]: ...
    def aiter_raw(self, *, chunk_size: int | None = ...) -> AsyncIterator[bytes]: ...
    def read(self) -> bytes: ...
    async def aread(self) -> bytes: ...


class StreamingBytesIterator(Iterator[bytes]):
    def __next__(self) -> bytes: ...
class StreamingTextIterator(Iterator[str]):
    def __next__(self) -> str: ...
class StreamingLinesIterator(Iterator[str]):
    def __next__(self) -> str: ...
class StreamingRawBytesIterator(Iterator[bytes]):
    def __next__(self) -> bytes: ...
class AsyncStreamingBytesIterator(AsyncIterator[bytes]):
    async def __anext__(self) -> bytes: ...
class AsyncStreamingTextIterator(AsyncIterator[str]):
    async def __anext__(self) -> str: ...
class AsyncStreamingLinesIterator(AsyncIterator[str]):
    async def __anext__(self) -> str: ...
class AsyncStreamingRawBytesIterator(AsyncIterator[bytes]):
    async def __anext__(self) -> bytes: ...


class Client:
    def __init__(
        self,
        *,
        headers: HeadersInput | None = ...,
        timeout: float | Timeout | None = ...,
        follow_redirects: bool | None = ...,
        max_redirects: int | None = ...,
        cookies: Cookies | Mapping[str, str] | None = ...,
        auth: Auth | None = ...,
        decompress: bool | None = ...,
        proxy: str | None = ...,
        verify: Verify | None = ...,
        cert: Cert | None = ...,
        retries: Retry | None = ...,
        http1: bool | None = ...,
        http2: bool | None = ...,
        http3: bool | None = ...,
        limits: Limits | None = ...,
        trust_env: bool | None = ...,
        local_address: str | None = ...,
        socket_options: Sequence[tuple[int, ...]] | None = ...,
        uds: str | None = ...,
    ) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...
    def request(self, method: str, url: str, *, headers: HeadersInput | None = ..., params: Any = ..., content: SyncBody | None = ..., data: Any = ..., json: Any = ..., files: Any = ..., timeout: float | Timeout | None = ..., cookies: Cookies | Mapping[str, str] | None = ..., auth: Auth | None = ..., follow_redirects: bool | None = ..., max_redirects: int | None = ..., decompress: bool | None = ..., proxy: str | None = ..., verify: Verify | None = ..., cert: Cert | None = ..., retries: Retry | None = ..., extensions: Mapping[str, Any] | None = ...) -> Response: ...
    def get(self, url: str, **kwargs: Any) -> Response: ...
    def post(self, url: str, *, content: SyncBody | None = ..., **kwargs: Any) -> Response: ...
    def put(self, url: str, *, content: SyncBody | None = ..., **kwargs: Any) -> Response: ...
    def patch(self, url: str, *, content: SyncBody | None = ..., **kwargs: Any) -> Response: ...
    def delete(self, url: str, **kwargs: Any) -> Response: ...
    def head(self, url: str, **kwargs: Any) -> Response: ...
    def options(self, url: str, **kwargs: Any) -> Response: ...
    def stream(self, method: str, url: str, *, content: SyncBody | None = ..., **kwargs: Any) -> StreamingResponse: ...
    def close(self) -> None: ...


class AsyncClient:
    def __init__(self, **kwargs: Any) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...
    async def request(self, method: str, url: str, *, content: SyncBody | AsyncBody | None = ..., **kwargs: Any) -> Response: ...
    async def get(self, url: str, **kwargs: Any) -> Response: ...
    async def post(self, url: str, *, content: SyncBody | AsyncBody | None = ..., **kwargs: Any) -> Response: ...
    async def put(self, url: str, *, content: SyncBody | AsyncBody | None = ..., **kwargs: Any) -> Response: ...
    async def patch(self, url: str, *, content: SyncBody | AsyncBody | None = ..., **kwargs: Any) -> Response: ...
    async def delete(self, url: str, **kwargs: Any) -> Response: ...
    async def head(self, url: str, **kwargs: Any) -> Response: ...
    async def options(self, url: str, **kwargs: Any) -> Response: ...
    async def stream(self, method: str, url: str, *, content: SyncBody | AsyncBody | None = ..., **kwargs: Any) -> StreamingResponse: ...
    async def aclose(self) -> None: ...


def request(method: str, url: str, *, headers: HeadersInput | None = ..., params: Any = ..., content: SyncBody | None = ..., data: Any = ..., json: Any = ..., files: Any = ..., timeout: float | Timeout | None = ..., cookies: Cookies | Mapping[str, str] | None = ..., auth: Auth | None = ..., follow_redirects: bool | None = ..., max_redirects: int | None = ..., decompress: bool | None = ..., proxy: str | None = ..., verify: Verify | None = ..., cert: Cert | None = ..., retries: Retry | None = ..., limits: Limits | None = ...) -> Response: ...
def get(url: str, **kwargs: Any) -> Response: ...
def post(url: str, *, content: SyncBody | None = ..., **kwargs: Any) -> Response: ...
def put(url: str, *, content: SyncBody | None = ..., **kwargs: Any) -> Response: ...
def patch(url: str, *, content: SyncBody | None = ..., **kwargs: Any) -> Response: ...
def delete(url: str, **kwargs: Any) -> Response: ...
def head(url: str, **kwargs: Any) -> Response: ...
def options(url: str, **kwargs: Any) -> Response: ...

__version__: str
