from collections.abc import AsyncIterable, AsyncIterator, Iterable, Iterator, Mapping, Sequence
from typing import Any, Self, TypeAlias
BytesLike: TypeAlias = bytes | bytearray | memoryview
SyncBody: TypeAlias = BytesLike | str | Iterable[BytesLike | str]
AsyncBody: TypeAlias = AsyncIterable[BytesLike | str]
HeadersInput: TypeAlias = Mapping[str, str] | Sequence[tuple[str, str]]
class EggfetchError(Exception): ...
class RequestError(EggfetchError): ...
class InvalidUrl(RequestError): ...
class TimeoutException(RequestError): ...
class PoolTimeout(TimeoutException): ...
class ConnectTimeout(TimeoutException): ...
class ReadTimeout(TimeoutException): ...
class WriteTimeout(TimeoutException): ...
class NetworkError(RequestError): ...
class ProtocolError(RequestError): ...
class BodyError(RequestError): ...
class TooManyRedirects(RequestError): ...
class DecompressionError(RequestError): ...
class UnsupportedContentEncoding(RequestError): ...
class ProxyError(RequestError): ...
class ProxyConnectError(ProxyError): ...
class ProxyAuthError(ProxyError): ...
class BodyNotReplayableForRetry(RequestError): ...
class RetryBudgetExhausted(RequestError): ...
class RetryNotConfigured(RequestError): ...
class Http2Error(RequestError): ...
class Http2GoAway(Http2Error): ...
class Http2StreamReset(Http2Error): ...
class Http2FlowControlError(Http2Error): ...
class H3Error(RequestError): ...
class H3ConnectError(H3Error): ...
class H3ProtocolError(H3Error): ...
class HTTPStatusError(EggfetchError): ...
class UnsupportedKwarg(EggfetchError): ...
class StreamConsumed(EggfetchError): ...
class StreamClosed(EggfetchError): ...
class ResponseNotRead(EggfetchError): ...
class Headers:
    def __init__(self, value: HeadersInput | None = ..., **kwargs: str) -> None: ...
    def __getitem__(self, key: str) -> str: ...
    def __contains__(self, key: object) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def get(self, key: str, default: str | None = ...) -> str | None: ...
class Cookie: ...
class Cookies:
    def __init__(self, cookies: Mapping[str, str] | None = ...) -> None: ...
class Timeout: ...
class Limits: ...
class Retry: ...
class BasicAuth:
    def __init__(self, username: str, password: str = ...) -> None: ...
class BearerAuth:
    def __init__(self, token: str) -> None: ...
class NoAuth: ...
NOAUTH: NoAuth
class File: ...
class NetworkStream:
    def read(self, max_bytes: int = ..., timeout: float | None = ...) -> bytes: ...
    def write(self, data: bytes, timeout: float | None = ...) -> None: ...
    def close(self) -> None: ...
    def get_extra_info(self, key: str) -> str | None: ...
class AsyncNetworkStream:
    async def read(self, max_bytes: int = ..., timeout: float | None = ...) -> bytes: ...
    async def write(self, data: bytes, timeout: float | None = ...) -> None: ...
    async def aclose(self) -> None: ...
    def get_extra_info(self, key: str) -> str | None: ...
class Response:
    status_code: int
    headers: Headers
    url: str
    content: bytes
    text: str
    extensions: dict[str, Any]
    def json(self, **kwargs: Any) -> Any: ...
    def iter_bytes(self, chunk_size: int = ...) -> Iterator[bytes]: ...
    def iter_text(self, chunk_size: int = ...) -> Iterator[str]: ...
    def iter_lines(self) -> Iterator[str]: ...
    def raise_for_status(self) -> Response: ...
class StreamingResponse(Response):
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...
    def close(self) -> None: ...
class StreamingBytesIterator(Iterator[bytes]): ...
class StreamingTextIterator(Iterator[str]): ...
class StreamingLinesIterator(Iterator[str]): ...
class StreamingRawBytesIterator(Iterator[bytes]): ...
class AsyncStreamingBytesIterator(AsyncIterator[bytes]): ...
class AsyncStreamingTextIterator(AsyncIterator[str]): ...
class AsyncStreamingLinesIterator(AsyncIterator[str]): ...
class AsyncStreamingRawBytesIterator(AsyncIterator[bytes]): ...
class Client:
    def __init__(self, **kwargs: Any) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...
    def request(self, method: str, url: str, *, content: SyncBody | None = ..., **kwargs: Any) -> Response: ...
    def get(self, url: str, **kwargs: Any) -> Response: ...
    def post(self, url: str, *, content: SyncBody | None = ..., **kwargs: Any) -> Response: ...
    def put(self, url: str, *, content: SyncBody | None = ..., **kwargs: Any) -> Response: ...
    def patch(self, url: str, *, content: SyncBody | None = ..., **kwargs: Any) -> Response: ...
    def delete(self, url: str, **kwargs: Any) -> Response: ...
    def head(self, url: str, **kwargs: Any) -> Response: ...
    def options(self, url: str, **kwargs: Any) -> Response: ...
    def stream(self, method: str, url: str, *, content: SyncBody | None = ..., **kwargs: Any) -> StreamingResponse: ...
    def close(self) -> None: ...
class AsyncClient:
    def __init__(self, **kwargs: Any) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...
    async def request(self, method: str, url: str, *, content: SyncBody | AsyncBody | None = ..., **kwargs: Any) -> Response: ...
    async def get(self, url: str, **kwargs: Any) -> Response: ...
    async def post(self, url: str, *, content: SyncBody | AsyncBody | None = ..., **kwargs: Any) -> Response: ...
    async def put(self, url: str, *, content: SyncBody | AsyncBody | None = ..., **kwargs: Any) -> Response: ...
    async def patch(self, url: str, *, content: SyncBody | AsyncBody | None = ..., **kwargs: Any) -> Response: ...
    async def delete(self, url: str, **kwargs: Any) -> Response: ...
    async def head(self, url: str, **kwargs: Any) -> Response: ...
    async def options(self, url: str, **kwargs: Any) -> Response: ...
    async def stream(self, method: str, url: str, *, content: SyncBody | AsyncBody | None = ..., **kwargs: Any) -> Any: ...
    async def aclose(self) -> None: ...
def request(method: str, url: str, *, content: SyncBody | None = ..., **kwargs: Any) -> Response: ...
def get(url: str, **kwargs: Any) -> Response: ...
def post(url: str, *, content: SyncBody | None = ..., **kwargs: Any) -> Response: ...
def put(url: str, *, content: SyncBody | None = ..., **kwargs: Any) -> Response: ...
def patch(url: str, *, content: SyncBody | None = ..., **kwargs: Any) -> Response: ...
def delete(url: str, **kwargs: Any) -> Response: ...
def head(url: str, **kwargs: Any) -> Response: ...
def options(url: str, **kwargs: Any) -> Response: ...
__version__: str
